### ISSUE TITLE
Expand content for mixins on base/common page with examples for each

### ISSUE THREAD

**Issue by coenkoopmans** [kpn/kpn-style#11]
### Overview
Currently, a list of mixins is shown, as well as a few examples on how to use them. This is nice and workable, but lacks explanation. What does each of these mixins do? Do they accept arguments? Anything to keep in mind? Any concrete examples?

### Acceptance criteria
- [ ] Give each mixin a separate h4 heading.
- [ ] Write copy text for each mixin -- under its corresponding heading -- detailing what it does.
- [ ] Document every argument (required + optional) and return value.
- [ ] Add examples for each mixin with a code block and result.

**Comment by jordybulten** [comment]
Merged into #15
