### ISSUE TITLE
Move all "customizable variables" headings to the bottom of each documentation page

### ISSUE THREAD

**Issue by coenkoopmans** [kpn/kpn-style#24]
### Description
Currently, all pages that have them (such as button, input, and block) start with "Customizable variables". It is however not stated what exactly these variables do. It is more of an advanced feature for people who already understand the component better than someone who is taking their first look. For this reason, please move all the customizable variables to the bottom of all the relevant pages.

### Acceptance criteria

- [ ] "Customizable variables" parts all at the bottom

**Comment by jordybulten** [comment]
Merged with #15
