### ISSUE TITLE
combination of top-bar and mega-menu classes

### ISSUE THREAD

**Issue by thijs-creemers** [kpn/kpn-style#6]
When trying to use the KPN standard style in our project. I tried to combine the top-bar class with the mega-menu class. The height of the top bar is to low and the positioning of the title-bar is to high. I scanned the documentation but did not find anything about how to setup it in this combination.

**Comment by benbesuijen** [comment]
Hi Thijs,
The `top-bar` should be used for KPN apps/portals and the `mega-menu` for KPN websites/landing pages. Therefore they do not work together. Are you making an app or website?

**Comment by thijs-creemers** [comment]
Thanks for the info . 
We are making an app, I will change the menu tho a the top-bar__item class.

**Comment by benbesuijen** [comment]
You are welcome. I will improve our documentation to make this more clear.  

You can use the `side-bar` if you need a more complex navigation structure.
