### ISSUE TITLE
Going to a specific link in the docs does not work

### ISSUE THREAD

**Issue by Woile** [kpn/kpn-style#7]
**Current state**
Specific documentation links do not work.

**Desired state**
Going to a link like "side bar" should open the documentation there.

**Description**
Going to a link like: https://style.kpn.com/layout/side-bar throws a 404 not found. 
This is probably related somehow to react routes.

![image](https://user-images.githubusercontent.com/2585816/69555732-f011b680-0fa3-11ea-85fc-b9ce4fd8a5d8.png)

**Comment by benbesuijen** [comment]
Github pages does not support the React BrowserRouter so we changed to HashRouter
